config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get 'search' => 'searches#search'

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    # あるユーザーがフォローしている人を表示させるルーティング。on: :memberでidを含ませることができる
    get :followers, on: :member
    # あるユーザーをフォローしている人を表示させるルーティング。on: :memberでidを含ませることができる
  end

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :chats, only: [:show, :create]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    following = current_user.relationships.build(follower_id: params[:user_id])
    # following_idにはcurrent_user.idが入る
    # followerにはパラメーターから取ってきたuser_idが入る
    following.save
  end

  def destroy
    @user = User.find(params[:user_id])
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    # following_idにはcurrent_user.idが入る
    # followerにはパラメーターから取ってきたuser_idが入る
    following.destroy
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if user != current_user %>
  <% if user.is_followed_by?(current_user) %>
    <%= link_to user_relationships_path(user), method: :delete, remote:true do %>
      <button class="btn btn-danger">フォロー解除</button>
    <% end %>
  <% else %>
    <%= link_to user_relationships_path(user), method: :post, remote:true do %>
      <button class="btn btn-primary">フォロー</button>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/_follower_count.html.erb
フォロワー数:<%= user.followers.count %>

app/views/relationships/_follower_count_info.html.erb
<%= link_to followers_user_path(user) do %>
  <%= user.followers.count %>
<% end %>

app/views/relationships/_following_count.html.erb
フォロー数:<%= user.followings.count %>

app/views/relationships/_following_count_info.html.erb
<%= link_to followings_user_path(user) do %>
  <%= user.followings.count %>
<% end %>

app/views/relationships/create.js.erb
$('.follow_btn_<%= @user.id %>').html("<%= j(render 'relationships/follow', user: @user) %>")
$('.following_count_<%= @user.id %>').html("<%= j(render 'relationships/following_count', user: @user) %>")
$('.follower_count_<%= @user.id %>').html("<%= j(render 'relationships/follower_count', user: @user) %>")
$('.following_count_info_<%= @user.id %>').html("<%= j(render 'relationships/following_count_info', user: @user) %>")
$('.follower_count_info_<%= @user.id %>').html("<%= j(render 'relationships/follower_count_info', user: @user) %>")

app/views/relationships/destroy.js.erb
$('.follow_btn_<%= @user.id %>').html('<%= j(render 'relationships/follow', user: @user) %>')
$('.following_count_<%= @user.id %>').html('<%= j(render 'relationships/following_count', user: @user) %>')
$('.follower_count_<%= @user.id %>').html('<%= j(render 'relationships/follower_count', user: @user) %>')
$('.following_count_info_<%= @user.id %>').html('<%= j(render 'relationships/following_count_info', user: @user) %>')
$('.follower_count_info_<%= @user.id %>').html('<%= j(render 'relationships/follower_count_info', user: @user) %>')